// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ProAtiva.API.Data;

namespace ProAtiva.API.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20200301221017_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079");

            modelBuilder.Entity("ProAtiva.API.Model.Fundo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CnpjFundo");

                    b.Property<string>("FundoId");

                    b.Property<decimal>("InvestimentoInicialMin");

                    b.Property<string>("NomeFundo");

                    b.HasKey("Id");

                    b.ToTable("Fundos");
                });
#pragma warning restore 612, 618
        }
    }
}
